name: Update Languages Chart

on:
  schedule:
    - cron: '0 0 * * 0'  # يعمل كل أسبوع يوم الأحد عند منتصف الليل
  workflow_dispatch:  # يسمح بتشغيل يدوي
  push:
    branches: [ main ]
    paths: 
      - 'scripts/**'

jobs:
  update-languages-chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate languages chart
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
      run: |
        python scripts/generate_languages_chart.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add charts/
        git diff --staged --quiet || git commit -m "Update languages chart [skip ci]"
        git push